# Generated by Django 5.2 on 2025-05-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='company_name',
            field=models.CharField(default='Default Warehouse', max_length=100),
        ),
    ]
