# Generated by Django 5.2 on 2025-05-13 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('warehouses', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='stores.store')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='warehouses.warehouse')),
            ],
            options={
                'unique_together': {('store', 'warehouse')},
            },
        ),
    ]
